Two Probe String Tactic Selection
mtrberzi/z3 pull request #41
Opened 2021-03-01 19:07 UTC by FedericoAureliano

Word equation probe and algorithm selection based on this word equation probe and the conjunctive-fragment probe. 

Would be interesting to work in the "cheese" tactic, e.g. when there are no word equations.

2021-03-01 19:30 UTC, FedericoAureliano commented
Run with `z3 smt.string_solver=z3str3 smt.str.tactic=2probe` for word equation and conjunctive fragment probes; run with `z3 smt.string_solver=z3str3 smt.str.tactic=3probe` for those two probes plus a regex probe.

2021-03-02 17:28 UTC, FedericoAureliano commented on src/tactic/smtlogics/z3str3_tactic.cpp
> +                     or_else(z3str3_2, z3seqAfter)),
I worried we'd be relying on the sequence solver too much if we call it first (most) times. But I think you're right. It makes sense to call it first here. Adding now.

2021-03-02 17:30 UTC, mtrberzi requested changes

2021-03-02 17:30 UTC, mtrberzi commented on src/tactic/smtlogics/z3str3_tactic.cpp
> +                     or_else(z3seqBefore, z3str3_2, z3seqAfter)),
This should be `z3str3_1` instead of `z3seqAfter`

2021-03-02 17:30 UTC, mtrberzi commented on src/tactic/smtlogics/z3str3_tactic.cpp
> +                     or_else(z3seqBefore, z3str3_2, z3seqAfter)),
This should be `z3str3_1` instead of `z3seqAfter`

2021-03-02 17:42 UTC, FedericoAureliano commented on src/tactic/smtlogics/z3str3_tactic.cpp
> +                     or_else(z3seqBefore, z3str3_2, z3seqAfter)),
Yup, good catch. Done.

2021-03-02 18:01 UTC, mtrberzi approved these changes

2021-03-02 18:01 UTC, merged